apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
  namespace: vms
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-vm
    spec:
      domain:
        cpu:
          cores: 2
          socket: 1
          threads: 1
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
            - name: disk1
              disk:
                bus: virtio
          interfaces:
            - name: iface0
              bridge: {}
        memory:
          guest: 4Gi
        resources:
          requests:
            memory: 4Gi
            cpu: "2"
      volumes:
        - name: disk0
          containerDisk:
            image: ubuntu:20.04
            imagePullPolicy: Always
        - name: disk1
          containerDisk:
            image: ubuntu:20.04
            imagePullPolicy: Always
      nodeSelector:
        kubevirt.io/schedulable: "true"
