apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
  namespace: kubevirt
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-vm
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
            cpu: "2"
      volumes:
        - name: kubevirt-disk
          containerDisk:
            image: ubuntu:latest
      devices:
        disks:
          - name: kubevirt-disk
            disk:
              bus: virtio
