apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: google
spec:
  ports:
  - port: 7000
  selector:
    app: currencyservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: google
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.8.0
        ports:
        - containerPort: 7000
