apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # یا LoadBalancer اگر داری
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080  # در صورت نیاز دسترسی از بیرون
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
        ports:
        - containerPort: 8080
        env:
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
