apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  namespace: google
spec:
  ports:
  - port: 3550
  selector:
    app: productcatalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  namespace: google
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
      - name: productcatalog
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
        ports:
        - containerPort: 3550
