apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # برای استفاده از HTTP، اگر می‌خواهید از SSL استفاده کنید این خط را حذف کنید
spec:
  rules:
  - host: minio.local # دامنه‌ای که می‌خواهید به MinIO دسترسی داشته باشید
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service # نام سرویس MinIO شما
            port:
              number: 9000 # پورت MinIO (مطمئن شوید که پورت صحیح را وارد کرده‌اید)
